GET   http://127.0.0.1:3000/
content-type: application/json,
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlODUwMzlkZjhiZjY5MmEwOGQ5ODNiMiIsImlhdCI6MTU4NTc3NTUzMX0.kzyO-W3sNC8R5FZHKWz5v_-Q-bUqToNNAQlALTzc7QA

{
    "name":"Victorred",
    "password":"victorred",
    "updateStatus": "It's late at night tho"
}

